services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysql-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s


  react:
    build: ./client
    container_name: react-container
    image: react-image
    ports:
      - "5173:5173"
    command: npm run dev
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app_network

volumes:
  mysql-data:

networks:
  app_network:
