services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysql-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  couchdb:
    image: couchdb:latest
    container_name: couch-container
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - "5984:5984"
    volumes:
      - couchdb-data:/opt/couchdb/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    command: ["couchdb", "-c", "log.level=info"]

  express-mysql:
    build: ./server-mysql
    image: express-mysql-image
    container_name: express-mysql-container
    ports:
      - "8080:8080"
    command: npm run dev
    env_file:
      - ./server-mysql/.env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./server-mysql:/app
      - /app/node_modules
    networks:
      - app_network


  express-couch:
    build: ./server-couch
    image: express-couch-image
    container_name: express-couch-container
    ports:
      - "9090:9090"
    command: npm run dev
    env_file:
      - ./server-couch/.env
    depends_on:
      couchdb:
        condition: service_healthy
    volumes:
      - ./server-couch:/app
      - /app/node_modules
    networks:
      - app_network
    

  react:
    build: ./client
    container_name: react-container
    image: react-image
    ports:
      - "5173:5173"
    command: npm run dev
    env_file:
      - ./client/.env
    depends_on:
      - express-couch
      - express-mysql
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app_network

volumes:
  mysql-data:
  couchdb-data:

networks:
  app_network:
