const axios = require('axios');


/**
 * Sends a request to the express server to upload the image to couchdb.
 * @param {File} image The image file.
 * @returns The image id generated by couchdb.
 */
const uploadImage = async (image) => {
    try {

        const formData = new FormData();
        
        formData.append("image", image.buffer, {
            filename: "image",
            contentType: image.mimetype
        });

        const res = await axios.post(`${process.env.COUCHDB_BASE_URL}/upload-image`, 
            formData,
            { headers : formData.getHeaders()}
        );

        return res.data.imageId;
        
    } catch (error) {
        console.error("Error uploading image to couchdb");
    }
}


module.exports = uploadImage;